### ISSUE TITLE
How to control 2-Finger Gripper via MODBUS RTU ?

### ISSUE THREAD

**Issue by WwYyFan** [Orienfish/cautious-palm-tree#1]
hi @Orienfish 
I am using 2-Finger Gripper and I want to control its position, force speed using MODBUS RTU.
I follow the manual to control the robot.
Activation request: 09 10 03 E8 00 03 06 00 00 00 00 00 00 73 30
Closing the Gripper: 09 10 03 E8 00 03 06 09 00 00 FF FF FF 42 29
Opening the Gripper: 09 10 03 E8 00 03 06 09 00 00 00 FF FF 72 19
It all works just fine when closing and opening with full speed,full force.
But if I adjust the position, speed or force.It doesn't read the command and return nothing.
What command should I send to control position,speed and force ?

**Comment by Orienfish** [comment]
Hi,
I think the problem you have is that you need to recalculate the CRC. The modbus protocol has CRC checking bytes (the last two bytes), which needs to be correct to let it work. When you change the speed or force, you change some numbers in the command, thus the CRC checking bytes of this command should also be changed.
You can check for the examples on the [Gripper Instruction Manual](https://assets.robotiq.com/production/support_documents/document/2-Finger_PDF_20180403.pdf?_ga=2.98522783.16162222.1523848300-1328024031.1523237652) start from page 59. This will help you understand every elements in the command you used.
And I have a C version MODBUS RTU library for the 2-Finger Gripper [here](https://github.com/Orienfish/ur3-python/blob/master/modbusrtu.c).

**Comment by WwYyFan** [comment]
@Orienfish Thanks for your reply !  I will try it.
